In python3, input() returns a string, but in python2, input() essentially eval's the string. This means that when tying to run setup.py in python2, the following error is raised:
[i] Do you want to install with C-modules (requires Cython)? (Y/N) y
Traceback (most recent call last):
File "setup.py", line 21, in <module>
    answer = input("[i] Do you want to install with C-modules (requires Cython)? (Y/N) ")
    File "<string>", line 1, in <module>
NameError: name 'y' is not defined